// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future initializeApp() async => await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_SvfilUGBhX3FTc1R2DvvfC2h0CGKCo',
    appId: '1:806624052611:android:b42d2ab220779a9d2522b6',
    messagingSenderId: '806624052611',
    projectId: 'shop-app-5e60e',
    storageBucket: 'shop-app-5e60e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHGj-w6KPi7tzDEUi8E7hW3Rh5YagKpOA',
    appId: '1:806624052611:ios:46c4812d6916b65b2522b6',
    messagingSenderId: '806624052611',
    projectId: 'shop-app-5e60e',
    storageBucket: 'shop-app-5e60e.appspot.com',
    iosClientId:
        '806624052611-g9qvk7o02pil3mqddfljkagbis7b3nll.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
